services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"

  pgdb:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=concreteai
      - DB_PORT=5432
    ports:
      - 5434:5432
    volumes:
      - pgdb:/var/lib/postgres

  payment:
    build: ./payment_service
    depends_on:
      - pgdb
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./payment_service/.env

  account:
    build: ./account_service
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./account_service/.env

volumes:
  pgdb:
