services:
  pgdb:
    container_name: pgdb
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=concreteai
      - DB_PORT=5432
    ports:
      - 5434:5432
    volumes:
      - pgdb:/var/lib/postgres

  concreteai-account:
    container_name: account
    build: ./account_manager
    depends_on:
      - pgdb
    ports:
      - 8000:8000
    env_file:
      - ./account_manager/.env

volumes:
  pgdb:
